apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: pod-watcher
build:
  tagPolicy:
    gitCommit:
      variant: Tags
  artifacts:
    - image: pod-watcher
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - skaffold/deployment.yaml
      # - skaffold/serviceaccount.yaml
      # - skaffold/rolebinding.yaml
      # - skaffold/role.yaml
  kubeContext: minikube
