---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-watcher
  namespace: pod-watcher
  labels:
    app.kubernetes.io/name: pod-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pod-watcher
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pod-watcher
    spec:
      containers:
        - name: pod-watcher
          image: pod-watcher
          resources:
            limits:
              cpu: 2000m
              memory: 700Mi
            requests:
              cpu: 500m
              memory: 200Mi
