apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-watcher
  namespace: pod-watcher
rules:
  - apiGroups:
      - "apps"
      - "core"
      - ""
    verbs:
      - get
      - create
      - delete
      - deletecollection
      - patch
      - update
      - list
      - watch
    resources:
      - pods
      - deployments
      - daemonsets
